name: "Test own action"
on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - run: npm ci
    - uses: ./
    - run: |
        echo "$BRANCH_NAME"
        if [[ "$BRANCH_NAME" != 'main' ]]; then
          exit 1
        fi
